apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: logger:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080